### ISSUE TITLE
Handle start and end of stream

### ISSUE THREAD

**Issue by crackofdusk** [audiocogs/dgplayer#2]
The counter should be stopped and grayed out before the stream starts and after it ends. The play button, too. When a stream ends, show a link icon if the stream was uploaded to official.fm.

_Edited to take into account the start of a stream._

**Comment by crackofdusk** [comment]
Don't worry about that link icon, or whatever means we'll use to convey the idea. For now, we just need an inactive, grayed out play icon.

**Comment by devongovett** [comment]
It should also start in this state if the user isn't broadcasting when the page loads... Is it possible to know when they start broadcasting and enable the play button automatically without the user reloading?

**Comment by crackofdusk** [comment]
Well, the player is only created for valid stream IDs. The stream ID doesn't exist before the user starts broadcasting. Thus, nobody could access the page before the beginning of the broadcast.

(The above isn't the way it currently works, but it will be changed soon.)

**Comment by devongovett** [comment]
But what about embedded players? They just load nothing?

**Comment by crackofdusk** [comment]
Until now we've assumed that a technician would be taking care of the broadcast and embeds while the musicians are permorming. However, I don't know how valid this assumption is. We need to think it through.

@nddrylliog, what do you think?

**Comment by nddrylliog** [comment]
@happydawn I think @devongovett is right: people can access even a profile page while it's not streaming, and the player should just be greyed out (with the metadata feed stating: broadcasting hasn't begun yet), and it would ungray when the stream has started

**Comment by crackofdusk** [comment]
Er... a profile page or a stream page? I agree with both of you, but streams are available at /live/streamid whereas profiles will be available at /profile/username or whatever and profiles do not necessarily embed a player.

**Comment by nddrylliog** [comment]
Hmm why would profile pages not embed a player?

**Comment by crackofdusk** [comment]
Depends on what info we want to show on the page. Latest/current broadcast? Anyway, this is irrelevant in this issue.

I edited the issue to take into account both the start and the end of stream. @devongovett, we agree then.
