### ISSUE TITLE
The startTime isn't very intuitive for a player that isn't streaming

### ISSUE THREAD

**Issue by jussi-kalliokoski** [audiocogs/dgplayer#6]
An alternative would be an additional accessor to the innerHTML of the counter, such as `currentTime`.

**Comment by devongovett** [comment]
Well you just wouldn't use the `startTime` property at all in that case right?  For a non-streaming player we're going to have to change a lot anyway... There are a few things that are shared, but a non streaming player has a lot of different things as well.  I haven't figured out the best way to do that yet.
