### ISSUE TITLE
How i feeling end of file

### ISSUE THREAD

**Issue by master255** [audiocogs/dgplayer#9]
Where, how method to get a event - "file is end"???
I wont simply play new file after current is end.

**Comment by crackofdusk** [comment]
Hello,

dgplayer is just a user interface. It doesn't know anything about audio playback. It does not know when a file has ended playing.

The way it works is that you need to connect interface events (such as, dgplayer's 'play' event, which occurs when the play button is pressed) to the actual player and events from the actual player to the interface.

In this case the underlying player itself should know when a file has ended playing and update dgplayer's properties to reflect this in the UI.

**Comment by master255** [comment]
right answer: player.player.on ('end', function() {})
And for volume change player.ui.on('volume', function() {})
